spring:
  application:
    name: sistema-ropa-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:tiendaropa}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Ifv.891123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

whatsapp:
  phone-number-id: 1046206528570803
  access-token: EAAWQBFVu9lIBRqK211heVttPVcnskz7du7nMegV3B9cxdYLPKhY1ZBQ0hVBJ7aiBtS3x3UcumOnJHSAUA7IWZAYyk95Mu220j2G8phdNjjoumzzMI7w52cZCZAmvJEeHgu8J0IR5aztiiMae6NlErNFhhWjCTq3P3jgumPuZBzFZB5IzWYHfGw0HjvOArxXzGC1wZDZD
  verify-token: jireh_webhook_2025
  business-account-id: 1676627570373964
